models/player/pacman/pacman.mdl
models/player/pac_ghost/pac_ghost.mdl
models/duckhunt/apple.mdl
models/duckhunt/cherry.mdl
models/duckhunt/peach.mdl
models/duckhunt/pear.mdl
models/duckhunt/pretzel.mdl
models/duckhunt/strawberry.mdl
models/duckhunt/pellet.mdl
models/duckhunt/pelletT.mdl
models/duckhunt/powerpellet.mdl
sound/duckhunt/pac_powerup.wav
sound/duckhunt/pac_start.wav
sound/duckhunt/pac_die.wav
sound/duckhunt/pac_bonus.wav
sound/duckhunt/pac_ghosteat.wav
sound/duckhunt/pac_chomp.wav
maps/dha_pacman_b4.txt