// K_TheGame2_r.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (112):
decals.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
liquids.wad
models/apache.mdl
models/barney.mdl
models/bluebird.mdl
models/chumtoad.mdl
models/deadhaz.mdl
models/fleshgibs.mdl
models/gman.mdl
models/hassassin.mdl
models/headcrab.mdl
models/houndeye_dead.mdl
models/plant_palm.mdl
models/skeleton.mdl
models/w_grenade.mdl
models/zombie.mdl
sound/ambience/alien_humongo.wav
sound/ambience/alien_minddrill.wav
sound/ambience/burning1.wav
sound/ambience/computalk1.wav
sound/ambience/cricket.wav
sound/ambience/particle_suck1.wav
sound/ambience/rifle1.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocketflame1.wav
sound/ambience/squeeks1.wav
sound/ambience/squitch.wav
sound/ambience/tankdrivein2.wav
sound/ambience/techamb2.wav
sound/ambience/truck2.wav
sound/ambience/waterfall2.wav
sound/ambience/xtal_down1.wav
sound/apache/ap_rotor3.wav
sound/apache/ap_rotor4.wav
sound/barney/ba_die2.wav
sound/barney/c2a5_ba_helpme.wav
sound/debris/beamstart2.wav
sound/debris/bustmetal1.wav
sound/debris/metal1.wav
sound/debris/metal3.wav
sound/debris/metal4.wav
sound/garg/gar_attack1.wav
sound/garg/gar_step1.wav
sound/garg/gar_step2.wav
sound/gonarch/gon_die1.wav
sound/headcrab/hc_alert1.wav
sound/headcrab/hc_die1.wav
sound/headcrab/hc_headbite.wav
sound/hgrunt/c2a3_ambush_fx.wav
sound/hgrunt/c2a5_hg_abandon.wav
sound/hgrunt/gr_alert1.wav
sound/hgrunt/gr_die1.wav
sound/hgrunt/gr_die2.wav
sound/hgrunt/gr_mgun1.wav
sound/Kristine/54moon.wav
sound/Kristine/airplant.wav
sound/Kristine/baahish.wav
sound/Kristine/chopper.wav
sound/Kristine/cluck2.wav
sound/Kristine/Congrats.wav
sound/Kristine/honkhonk.wav
sound/Kristine/intruder.wav
sound/Kristine/k_tg2.wav
sound/Kristine/keys.wav
sound/Kristine/nightmare.wav
sound/Kristine/opera.wav
sound/Kristine/ribbit.wav
sound/scientist/c1a0_sci_catscream.wav
sound/scientist/c1a0_sci_dis11a.wav
sound/scientist/c1a0_sci_dis12a.wav
sound/scientist/c1a0_sci_dis14a.wav
sound/scientist/c1a0_sci_dis15a.wav
sound/scientist/c1a0_sci_dis1a.wav
sound/scientist/c1a0_sci_dis1b.wav
sound/scientist/c1a0_sci_dis1c.wav
sound/scientist/c1a0_sci_dis2a.wav
sound/scientist/c1a0_sci_dis3a.wav
sound/scientist/c1a0_sci_dis5a.wav
sound/scientist/c1a0_sci_dis6a.wav
sound/scientist/c1a0_sci_dis7a.wav
sound/scientist/c1a0_sci_disa.wav
sound/tentacle/te_death2.wav
sound/weapons/egon_off1.wav
sound/weapons/explode3.wav
sound/weapons/gauss2.wav
sound/weapons/mine_activate.wav
sound/x/x_attack1.wav
sound/x/x_attack2.wav
sound/x/x_attack3.wav
sound/x/x_die1.wav
sound/x/x_laugh1.wav
sound/x/x_laugh2.wav
sound/zombie/zo_attack1.wav
sprites/b-tele1.spr
sprites/explode1.spr
sprites/hotglow.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/wallpuff.spr
sprites/xffloor.spr
tfc.wad
tfc2.wad
xeno.wad
