// K_TheGame.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (87):
decals.wad
gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
halflife.wad
liquids.wad
models/bluebird.mdl
models/headcrab.mdl
models/houndeye.mdl
models/skeleton.mdl
sound/ambience/computalk1.wav
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/industrial3.wav
sound/ambience/jetflyby1.wav
sound/ambience/siren.wav
sound/ambience/the_horror2.wav
sound/ambience/the_horror4.wav
sound/apache/ap_rotor2.wav
sound/barney/c1a0_ba_desk.wav
sound/barney/c1a2_ba_4zomb.wav
sound/barney/c2a4_ba_arg1a.wav
sound/barney/c2a4_ba_arg3a.wav
sound/barney/c2a4_ba_arg5a.wav
sound/debris/beamstart7.wav
sound/doors/doormove10.wav
sound/garg/gar_attack1.wav
sound/garg/gar_attack2.wav
sound/gonarch/gon_die1.wav
sound/headcrab/hc_alert1.wav
sound/headcrab/hc_attack2.wav
sound/hgrunt/c2a3_ambush_fx.wav
sound/houndeye/he_alert3.wav
sound/houndeye/he_attack1.wav
sound/houndeye/he_blast3.wav
sound/Kristine/cluck2.wav
sound/Kristine/Congrats.wav
sound/kristine/intro_seq3.wav
sound/kristine/opfor1.wav
sound/scientist/c1a1_sci_1scan.wav
sound/scientist/c1a1_sci_2scan.wav
sound/scientist/c1a1_sci_3scan.wav
sound/scientist/c1a3_sci_thankgod.wav
sound/scientist/c1a4_sci_pwr.wav
sound/scientist/c1a4_sci_pwroff.wav
sound/scientist/c1a4_sci_tent.wav
sound/scientist/c2a4_sci_arg2a.wav
sound/scientist/c2a4_sci_arg4a.wav
sound/scientist/c3a2_sci_7surv.wav
sound/scientist/c3a2_sci_notyet.wav
sound/scientist/c3a2_sci_portal.wav
sound/scientist/c3a2_sci_portopen.wav
sound/scientist/c3a2_sci_position.wav
sound/scientist/donuteater.wav
sound/scientist/holdstill.wav
sound/scientist/howinteresting.wav
sound/scientist/letstrythis.wav
sound/scientist/lowervoice.wav
sound/scientist/noo.wav
sound/scientist/odorfromyou.wav
sound/scientist/ofcoursenot.wav
sound/scientist/okgetout.wav
sound/scientist/perfectday.wav
sound/scientist/perhaps.wav
sound/scientist/repeat.wav
sound/scientist/runtest.wav
sound/scientist/scream01.wav
sound/scientist/yees.wav
sound/tentacle/te_death2.wav
sound/tentacle/te_sing1.wav
sound/tentacle/te_sing2.wav
sound/vox/bloop.wav
sound/weapons/mine_activate.wav
sound/weapons/mine_charge.wav
sound/weapons/mine_deploy.wav
sound/weapons/mortar.wav
sound/weapons/mortarhit.wav
sound/x/x_die1.wav
sprites/b-tele1.spr
sprites/ballsmoke.spr
sprites/rain.spr
tfc.wad
tfc2.wad
xeno.wad
